name: yume_kitai
description: "Revitalize your dreams."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^2.4.4
  go_router: ^14.6.2
  json_annotation: ^4.9.0
  logging: ^1.3.0
  provider: ^6.1.2
  smooth_corner:
    path: smooth_corner/
  sqflite: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.14
  freezed: ^2.5.8
  json_serializable: ^6.9.3

flutter:
  fonts:
    - family: NunitoSans
      fonts:
        - asset: assets/fonts/NunitoSans.ttf
  assets:
    - assets/images/YumeLogo.png
    - assets/images/Java.png
  uses-material-design: true
